x-docker-compose-project-name: inception

services:

  mariadb:
    build:
      context:  ./requirements/mariadb
      dockerfile : Dockerfile
      args:
          - WP_DATABASE=${WP_DATABASE}
          - WP_DBUSER=${WP_DBUSER}
          - WP_DBPASSWORD=${WP_DBPASSWORD}
    networks:
      mynetwork:
        aliases:
          - mariadb
    volumes:
        - mariadb_volume:/var/lib/mysql
    expose:
        - "3306"
    image: "mariadb"
    container_name: inception_mariadb

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
          - WP_DATABASE=${WP_DATABASE}
          - WP_DBUSER=${WP_DBUSER}
          - WP_DBPASSWORD=${WP_DBPASSWORD}
          - WP_DBHOST=${WP_DBHOST}
          - WP_ADMUSER=${WP_ADMUSER}
          - WP_ADMPASSWORD=${WP_ADMPASSWORD}
          - WP_ADMEMAIL=${WP_ADMEMAIL}
          - WP_USERNAME=${WP_USERNAME}
          - WP_USERPASSWORD=${WP_USERPASSWORD}
          - WP_USEREMAIL=${WP_USEREMAIL}
    networks:
      mynetwork:
        aliases:
          - wordpress
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    depends_on:
      - mariadb
    expose:
        - "9000"
    image: "wordpress"
    container_name: inception_wordpress
  
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - mynetwork
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    depends_on:
      - wordpress
    image: "nginx"
    container_name: inception_nginx

networks:
  mynetwork:
    name: inception_network 

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mgaldino/data/db
    name: mariadb_volume

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mgaldino/data/wordpress
    name: wordpress_volume
