services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - mynetwork

  mariadb:
    build:
      context:  ./mariadb
      dockerfile : Dockerfile
    networks:
      - mynetwork
    volumes:
        - myvolume:/var/lib/mysql

networks:
  mynetwork:


volumes:
  myvolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mgaldino/data
