services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - mynetwork

  mariadb:
    build:
      context:  ./mariadb
      dockerfile : Dockerfile
    networks:
      - mynetwork

networks:
  mynetwork:

