services:

  mariadb:
    build:
      context:  ./mariadb
      dockerfile : Dockerfile
    networks:
      mynetwork:
        aliases:
          - mariadb
    volumes:
        - mariadb_volume:/var/lib/mysql

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    networks:
      mynetwork:
        aliases:
          - wordpress
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    depends_on:
      - mariadb
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - mynetwork
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    depends_on:
      - wordpress

networks:
  mynetwork:

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mgaldino/data/db

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mgaldino/data/wordpress
